config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
  delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :videos
  root 'main#index'
  get '/abouts' =>"main#about"
  get '/contacts' =>"main#contacts"
  
  get '/yboard' =>"board#yboard"
  post '/ywrite' =>"board#ywrite"
  get'/ysingle/:id' =>"board#ysingle",  as: "ysingle"
  get '/board/ydel/:id' =>"board#ydel", as: "ydel"
  get '/board/yedit/:id' =>"board#yedit", as: "yedit"
  post '/yupdate' =>"board#yupdate"

  get '/oboard' =>"board#oboard"
  post '/owrite' =>"board#owrite"
  get'/osingle/:id' =>"board#osingle",  as: "osingle"
  get '/board/odel/:id' =>"board#odel", as: "odel"
  get '/board/oedit/:id' =>"board#oedit", as: "oedit"
  post '/oupdate' =>"board#oupdate"

  get '/announce' =>"board#announce"
  post  '/annwrt' =>"board#annwrt"

  get '/board_total' =>"board#total"
  post '/comment' =>"board#comment"
  
  get'/btest' =>"board#btest"
  get'/profile/:id' =>"board#profile", as: "profile"
  
  get '/ggallery' =>"gallery#games"
  get '/gaup' =>"gallery#gaup"
  post '/gcre' =>"gallery#gcre"
  get '/egallery' =>"gallery#event"
  get '/evup' =>"gallery#evup"
  post '/ecre' =>"gallery#ecre"
  get '/agallery' =>"gallery#aprivate"
  get '/prup' =>"gallery#prup"
  post '/acre' =>"gallery#acre"
  get '/tgallery' =>"gallery#total"
  
  

end

app/models/agal.rb
class Agal < ActiveRecord::Base
    belongs_to :user
    mount_uploader :image, AimageUploader
end

app/models/annct.rb
class Annct < ActiveRecord::Base
    has_many :comments
    belongs_to :user
    mount_uploader :image, AimageUploader
    self.per_page = 3    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :yblog
    belongs_to :oblog
    belongs_to :annct
    belongs_to :user
    has_many :users
end

app/models/egal.rb
class Egal < ActiveRecord::Base
    belongs_to :user
    mount_uploader :image, AimageUploader
end

app/models/ggal.rb
class Ggal < ActiveRecord::Base
    belongs_to :user
    mount_uploader :image, AimageUploader
end

app/models/oblog.rb
class Oblog < ActiveRecord::Base
    has_many :comments
    belongs_to :user
    mount_uploader :image, AimageUploader
    self.per_page = 3    

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :image, AimageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  devise :database_authenticatable, :validatable, password_length: 1..12
  
  has_many :yblogs
  has_many :oblogs
  has_many :anncts
  has_many :comments
  has_many :egals
  has_many :ggals
  has_many :agals
  belongs_to :comments
    
end

app/models/yblog.rb
class Yblog < ActiveRecord::Base
    has_many :comments
    belongs_to :user
    mount_uploader :image, AimageUploader
    self.per_page = 3    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :classid, :image, :phone, :aloca, :image, :image_cache) }
        end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
    before_action :authenticate_user!, except: :announce

    def announce
        @ablogs = Annct.all.reverse
    end

    def annwrt
        Annct.create(user_id: current_user.id, content: params[:acon], image: params[:aimage])
        redirect_to controller: 'board', action: 'announce'
    end
    
    def annedit
    end
    
    def anndel
    end
    
    def oboard
        @oblogs = Oblog.all.paginate(:page => params[:page]).order('id DESC')
        @users = User.all
    end

    def osingle
        @osingle = Oblog.find(params[:id])
        #Ysingle.create(user_id: current_user.id, blog_id: params[:blog_id], content: params[:ycon], image: params[:yimage], url: params[:yvideo])

        render controkker: 'board', action: 'osingle'
    end

    def owrite
        Oblog.create(user_id: current_user.id, content: params[:ocon], image: params[:oimage])
        redirect_to controller: 'board', action: 'oboard'
    end
    
    def oedit
    end
    
    def odel
    end
        
    def yboard
        @yblogs = Yblog.all.paginate(:page => params[:page]).order('id DESC')
        @users = User.all
    end
    
    def ysingle
        @ysingle = Yblog.find(params[:id])
        #Ysingle.create(user_id: current_user.id, blog_id: params[:blog_id], content: params[:ycon], image: params[:yimage], url: params[:yvideo])

        render controkker: 'board', action: 'ysingle'
    end
    
    def btest
        @yblogs = Yblog.all
    end
    
    def ywrite
        Yblog.create(user_id: current_user.id, content: params[:ycon], image: params[:yimage], url: params[:yvideo])
        redirect_to controller: 'board', action: 'yboard'
    end
    
    def yedit
        @ye = Yblog.find(params[:id])
    end
    
    def yupdate
        pup = Yblog.find(params[:id])
        pup.content = params[:ycon]
        pup.image = params[:yimage] 
            if params[:yimage].nil?
                pup.image = Yblog.find(params[:id]).image 
            end
        pup.url = params[:yvideo] 
            if params[:yvideo] == "" 
               pup.url = Yblog.find(params[:id]).url 
            end
        pup.save
        redirect_to controller: 'board', action: 'yboard'
    end
    
    def ydel
        yp = Yblog.find(params[:id])
        yp.destroy
        redirect_to controller: 'board', action: 'yboard'
    end
    
    def total
        @ablogs = Annct.all
        @oblogs = Oblog.all
        @yblogs = Yblog.all
    end
    
    def comment
        Comment.create(user_id: current_user.id, yblog_id: params[:yblog_id], msg: params[:comment])
        Comment.create(user_id: current_user.id, oblog_id: params[:oblog_id], msg: params[:comment])
        Comment.create(user_id: current_user.id, annct_id: params[:annct_id], msg: params[:comment])
        #Comment.create(user_id: current_user.id, pblog_id: params[:pblog_id], msg: params[:comment])
        redirect_to :back
    end
    

    def profile
        @profile = User.find(params[:id])
        #Ysingle.create(user_id: current_user.id, blog_id: params[:blog_id], content: params[:ycon], image: params[:yimage], url: params[:yvideo])

        render controkker: 'board', action: 'profile'
    end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
    def games
        @ggals = Ggal.all
    end
    
    def gaup
    end
    
    def gcre
        Ggal.create(user_id: current_user.id, title: params[:gtit], content: params[:gcon], image: params[:gimage])
        redirect_to controller: 'gallery', action: 'games'
    end

    def event
        @egals = Egal.all
    end
    
    def evup
    end
    
    def ecre
        Egal.create(user_id: current_user.id, title: params[:etit], content: params[:econ], image: params[:eimage])
        redirect_to controller: 'gallery', action: 'event'
    end

    def aprivate
        @agals = Agal.all
    end
    
    def prup
    end
    
    def acre
        Agal.create(user_id: current_user.id, title: params[:atit], content: params[:acon], image: params[:pimage])
        redirect_to controller: 'gallery', action: 'aprivate'
    end
    
    def total
        @ggals = Ggal.all
        @egals = Egal.all
        @agals = Agal.all
    end



end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def contacts
        @users = User.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/board/announce.html.erb
<h1>공지사항</h1>
<%=form_tag '/annwrt', method: 'post', multipart: true do %>
    <textarea name="acon"></textarea>
    <%= file_field_tag 'aimage' %>
    <input type="submit">
<% end %>
<ul>
    <% @ablogs.each do |ab| %>
    <li>
        <%=ab.content%>
        <img src="<%=ab.image.url%>" width="200px">
        <%=form_tag '/comment', method: 'post' do %>
        <input type="hidden" name="annct_id" value=" <%=ab.id%>">
        <input type="text" name="comment">
        <input type="submit">
        <% end %>
            <ol>
                <% ab.comments.each do |ca| %>
                    <li><%=ca.msg%></li>
                <% end %>
            </ol>
    </li>
    <% end %>
</ul>
    

app/views/board/osingle.html.erb
        <!--/start-main-->
          <div class="main-content">
		      <!--/soccer-inner-->
	                 <div class="soccer-inner">
					  <!--/soccer-left-part-->
					  <div class="col-md-8 soccer-left-part  blog">
					    <!--/about-->
						<div class="blogs">
						    <h3 class="tittle">Details</h3>
					        <div class="blog-grid">
						    <% if @osingle.image? %>
							    <img src="<%=@osingle.image.url%>" class="img-responsive" alt="" />
						    <% else %>
						    <% end %>
						    <% if @osingle.url? %>
					        <iframe src="<%=@osingle.url.gsub('watch?v=', 'embed/') %>" width="500px"></iframe>
						    <% else %>
						    <% end %>
							</div>
							 <div class="single-bottom">
							 <p><%=@osingle.content%></p>
					    </div>
						<div class="response">
					<h4>Comments</h4>
               <% @osingle.comments.each do |co| %>
					<div class="media response-info">
						<div class="media-left response-text-left">
							<a href="#">
								<img class="media-object" src="<%=co.user.image.url%>" alt=""/>
							</a>
							<h5><a href="#"><%=co.user.username%></a></h5>
						</div>
						<div class="media-body response-text-right">
							<p><%=co.msg%></p><p><%=co.created_at%></p>
						</div>
					</div>
				<% end %>
				</div>	
				<div class="coment-form">
					<h4>Leave your comment</h4>

        <%=form_tag '/comment', method: 'post' do %>
        <input type="hidden" name="oblog_id" value=" <%=@osingle.id%>">
        <input type="text" name="comment">
        <input type="submit">
        <% end %>
				</div>	
				<div class="clearfix"></div>

				</div>
					
			</div>
					<!--//soccer-left-part-->
		           <div class="clearfix"> </div>
	           </div>
			</div>
		<!--//soccer-inner-->
	 </div>

app/views/board/profile.html.erb
<h1>My page</h1>
<div class="main-content" style="margin-bottom:-50px">
<% if @profile.id == current_user.id %>
<div class="media response-info" style="margin-top:-50px">
    <div class="media-left response-text-left">
<ul>
    <li>name : <b><%=@profile.username%></b></li>
    <li>email : <b><%=@profile.email%></b></li>
    <li>학번 : <b><%=@profile.classid%></b></li>
    <% if @profile.image? %>
    <li> <img src="<%=@profile.image.url%>" class="media-object" width="200px"></li>
    <% else %>
    <li>사진 올릴 수 있음 (Edit로 가서)</li>
    <% end %>
    <br>
    <li>Posts by <%=@profile.username%></li>
    <% @profile.yblogs.each do |py| %>
    <ul>
        <%= link_to ysingle_path(py.id) do %>
        <li><%=py.content%></li>
        <% end %>
    </ul>
    <% end %>
    <% @profile.oblogs.each do |oy| %>
    <ul><li> <%=oy.content%></li></ul>
    <% end %>
    <% @profile.anncts.each do |ay| %>
    <ul><li> <%=ay.content%></li></ul>
    <% end %>
</ul>
    </div>
</div>
<br><br>
<div><a href="/users/edit">Edit My Profile</a></div>
<% else %>
<div class="media response-info">
    <div class="media-left response-text-left">
<ul>
    <li>name: <%=@profile.username%></li>
    <li>email : <%=@profile.email%></li>
    <li>학번 : <%=@profile.classid%></li>
    <% if @profile.image? %>
    <li> <img src="<%=@profile.image.url%>" class="media-object" width="200px"></li>
    <% else %>
    <% end %>
    <li><%=@profile.username%>가 쓴 글들</li>
    <% @profile.yblogs.each do |py| %>
        <%= link_to ysingle_path(py.id) do %>
        <div><%=py.content%></div>
        <% end %>
    <% end %>
    <br>
    
    
    <%=form_tag '/coment', method: 'post' do %>
    <input type="hidden" name="pblog_id" value=" <%=current_user.id%>">
    <textarea name="pcon" placeholder="<%=@profile.username%>에 대한 한줄평"></textarea>
    <input type="submit">
    <% end %>
        <div>
        <div>




</ul>
    </div>
</div>

<% end %>
</div>

app/views/board/total.html.erb
<h1>전체 게시판 보기</h1>
<ul>
    <% @yblogs.each do |y| %>
    <li>
        <%=y.content%>
            <ol>
                <% y.comments.each do |cy| %>
                    <li><%=cy.msg%></li>
                <% end %>
            </ol>
    </li>
    <% end %>
    <% @oblogs.each do |ob| %>
    <li>
        <%=ob.content%>
            <ol>
                <% ob.comments.each do |co| %>
                    <li><%=co.msg%></li>
                <% end %>
            </ol>
    </li>
    <% end %>
    <% @ablogs.each do |ab| %>
    <li>
        <%=ab.content%>
            <ol>
                <% ab.comments.each do |ca| %>
                    <li><%=ca.msg%></li>
                <% end %>
            </ol>
    </li>
    <% end %>


</ul>
    

app/views/board/yedit.html.erb
<h1>Edit your post</h1>

<%=form_tag '/yupdate', method: 'post', multipart: true do %>
    <input type="hidden" name="id" value="<%=@ye.id%>">
    <textarea name="ycon"><%=@ye.content%></textarea>
    <% if @ye.image? %>
      <div width="100px"><%= image_tag @ye.image.url , height: '132', width: '132' %></div><br/>
    <% end %>
    <%= file_field_tag 'yimage'%><br>
    <% if @ye.url? %>
    <textarea width="100px"><%=@ye.url%></textarea>
    <% end %>
    <%= text_field_tag 'yvideo', nil, :placeholder => 'Copy the URL link here' %>
    <input type="submit">
<% end %>

app/views/board/ysingle.html.erb
        <!--/start-main-->
          <div class="main-content">
		      <!--/soccer-inner-->
	                 <div class="soccer-inner">
					  <!--/soccer-left-part-->
					  <div class="col-md-8 soccer-left-part  blog">
					    <!--/about-->
						<div class="blogs">
						    <h3 class="tittle"><%=@ysingle.user.username%>'s Post</h3>
					        <div class="blog-grid">
						    <% if @ysingle.image? %>
							    <img src="<%=@ysingle.image.url%>" class="img-responsive" alt="" />
						    <% else %>
						    <% end %>
						    <% if @ysingle.url? %>
					        <iframe src="<%=@ysingle.url.gsub('watch?v=', 'embed/') %>" width="100%" height="500"></iframe>
						    <% else %>
						    <% end %>
							</div>
							 <div class="single-bottom">
							 <p><%=@ysingle.content%></p>
					     <% if @ysingle.user.id == current_user.id %>
						    <%= link_to ydel_path(@ysingle) do %> Del <% end %>
						    <%= link_to yedit_path(@ysingle) do %> Edit <% end %>
						 <% else %>
					     <% end %>


					    </div>
						<div class="response">
               <% @ysingle.comments.each do |cy| %>
					<div class="media response-info">
						<div class="media-left response-text-left">
							<%= link_to profile_path(cy.user.id) do %>
								<div>
								<img class="media-object" src="<%=cy.user.image.url%>" alt="" width="50px" style="float:left;"/>
								<h5 style="float:left;"> &nbsp; <%=cy.user.username%></h5>
								</div>
							<% end %>
						</div>
						<div class="media-body response-text-right">
							<p><%=cy.msg%> (<%=cy.created_at.strftime("%d %b. %Y, %H:%M")%>)</p>
						</div>
					</div>
				<% end %>
				</div>	
				<div class="coment-form">
					<h4>답글 남기기</h4>

        <%=form_tag '/comment', method: 'post' do %>
        <input type="hidden" name="yblog_id" value=" <%=@ysingle.id%>">
        <input type="text" name="comment">
        <input type="submit">
        <% end %>
				</div>	
				<div class="clearfix"></div>

				</div>
					
			</div>
					<!--//soccer-left-part-->
		           <div class="clearfix"> </div>
	           </div>
			</div>
		<!--//soccer-inner-->
	 </div>

app/views/gallery/aprivate.html.erb
          <div class="main-content">
		     <!--/gallery-->
			 <div class="gallery">
					<h3 class="tittle">Event Gallery</h3>
					<a href="/prup">upload</a>
					<div class="gallery-bottom grid">
<% @agals.each do |ag| %>
						<div class="col-md-3 g-left">
								<a href="<%=ag.image.url%>" rel="title" class="b-link-stripe b-animate-go  thickbox">
									<figure class="effect-oscar">
										<img src="<%=ag.image.url%>" alt=""/>
										<figcaption>
											<h4><%=ag.title%></h4>
											<p>by <%=ag.user.username%></p>
											<p><%=ag.content%></p>
										</figcaption>			
									</figure>
								</a>
							</div>
<% end %>
						<div class="clearfix"> </div>
						</div>
					</div>
			</div>

	         <!--//gallery-->
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AIR eveywhere</title>
  <!--
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  -->

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="AIR everywhere" />
  <script type="text/javascript" src="/javascripts/application.js"></script>
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
  <link href="/css/bootstrap-3.1.1.min.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/application.css" rel="stylesheet" type="text/css">
  <!-- Custom Theme files -->
  <link href="/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all" />
  <link href="/css/style.css" rel='stylesheet' type='text/css' />	
  <script src="/js/jquery.min.js"> </script>
  <script type="text/javascript" src="/js/move-top.js"></script>
  <script type="text/javascript" src="/js/easing.js"></script>
  <!--/script-->
  <script type="text/javascript">
  			jQuery(document).ready(function($) {
  				$(".scroll").click(function(event){		
  					event.preventDefault();
  					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
  				});
  			});
  </script>
  <script src="/js/modernizr.custom.97074.js"></script>
  <script src="/js/jquery.chocolat.js"></script>
  <link rel="stylesheet" href="/css/chocolat.css" type="text/css" media="screen" charset="utf-8">
		<!--light-box-files -->
  <script type="text/javascript">
		$(function() {
			$('.gallery-bottom a').Chocolat();
		});
  </script>


</head>
<body>
 <div class="container">
  <div class="header" id="home">
	 <div class="subhead white">
		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/"><h1>AIR <span>ball</span></h1> </a>
			</div>
			<!--/.navbar-header-->
		
			<div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					 <li><a href="/abouts">About</a></li>
				    <li class="dropdown">
						<a href="schedule.html" class="dropdown-toggle" data-toggle="dropdown">Board<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="/announce">공지사항</a></li>
							<li class="divider"></li>
							<li><a href="/oboard">OB방</a></li>
							<li class="divider"></li>
							<li><a href="/yboard">YB방</a></li>
							<li class="divider"></li>
							<li><a href="/board_total">전체보기</a></li>
							<!--<li class="divider"></li>
							<li><a href="schedule.html">One more separated link</a></li>-->
						</ul>
					  </li>
					<!--<li><a href="blog.html">Blogs</a></li> -->
					  <li class="dropdown">
						<a href="typo.html" class="dropdown-toggle" data-toggle="dropdown">Gallery<b class="caret"></b></a>
						<ul class="dropdown-menu multi-column columns-2">
							<div class="row">
								<div class="col-sm-6">
									<ul class="multi-column-dropdown">
										<li><a href="/ggallery">시합</a></li>
										<li class="divider"></li>
										<li><a href="/egallery">행사</a></li>
									    <li class="divider"></li>
										<li><a href="/agallery">개인사</a></li>
										<li class="divider"></li>
										<li><a href="/tgallery">모두 보기</a></li>
										<!--<li class="divider"></li>
										<li><a href="typo.html">Short codes</a></li>-->
									</ul>
								</div>
								<!-- <div class="col-sm-6">
									<ul class="multi-column-dropdown">
									   <li><a href="#">Features</a></li>	
										<li class="divider"></li>
										<li><a href="#"> Movies</a></li>
									    <li class="divider"></li>
										<li><a href="#">Sports</a></li>
										<li class="divider"></li>
										<li><a href="#">Reviews</a></li>
										<li class="divider"></li>
										<li><a href="#">Account</a></li>
									</ul>
								</div> -->
							</div>
						</ul>
					</li>
					<!--<li><a href="gallery.html">Gallery</a></li>-->
  					<li><a href="/contacts">Members</a></li>
  					<% if user_signed_in? %>
					<li><%= link_to "My Page", profile_path(current_user.id) %></li>
					<li><%=link_to "Logout", destroy_user_session_path, :method => :delete %></li>
					<!--<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Logout</a></li>-->
 					<% else %>
					<li><a href="/users/sign_in">Log in</a></li>
  					<% end %>
				</ul>
			</div>
			<!--/.navbar-collapse-->
	 <!--/.navbar-->
	</nav>
  </div>
 </div>



<%= yield %>




	<!--/start-footer-section-->
	<!--
			<div class="footer-section">
			   <div class="container">
					<div class="footer-grids">
						<div class="col-md-4 footer-grid">
						<h4><span>LATEST</span> PICKS</h4>
						  <div class="editor-pics">
							 <div class="col-md-3 item-pic">
							   <img src="/images/f1.jpg" class="img-responsive" alt=""/>

							   </div>
					   	        <div class="col-md-9 item-details">
							    	<h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
								      <div class="td-post-date">Feb 22, 2015</div>
							     </div>
								<div class="clearfix"></div>
							</div>
							 <div class="editor-pics">
							 <div class="col-md-3 item-pic">
							   <img src="/images/f2.jpg" class="img-responsive" alt=""/>

							   </div>
					   	        <div class="col-md-9 item-details">
							    	<h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
								      <div class="td-post-date">Feb 22, 2015</div>
							     </div>
								<div class="clearfix"></div>
							</div>
		
						</div>
						<div class="col-md-4 footer-grid">
							<h4><span>POPULAR</span> POSTS</h4>
								<div class="editor-pics">
										 <div class="col-md-3 item-pic">
										   <img src="/images/f4.jpg" class="img-responsive" alt=""/>

										   </div>
											<div class="col-md-9 item-details">
												<h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
												  <div class="td-post-date">Feb 22, 2015</div>
											 </div>
											<div class="clearfix"></div>
										</div>
										<div class="editor-pics">
							 <div class="col-md-3 item-pic">
							   <img src="/images/f3.jpg" class="img-responsive" alt=""/>

							   </div>
					   	        <div class="col-md-9 item-details">
							    	<h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
								      <div class="td-post-date">Feb 22, 2015</div>
							     </div>
								<div class="clearfix"></div>
							</div>

						</div>
						<div class="col-md-4 footer-grid third">
								<h4><span>News</span>Letter</h4>
							       <div class="sign_up">
										<p class="sign">Sign up to receive our free newsletters!</p>
										<form>
											<input type="text" class="text" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
											<input type="text" class="text" value="Email Address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email Address';}">
											<input type="submit" value="submit">
										</form>
									</div>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
	-->		
	<!--//end-footer-section-->
			<!--/start-copyright-section-->
				<div class="copyright">
						  <p>&copy; 2016 AIR. All Rights Reserved | Design by <a href="http://w3layouts.com/">AIR</a> </p>
					</div>


				<!--start-smoth-scrolling-->
						<script type="text/javascript">
									$(document).ready(function() {
										/*
										var defaults = {
								  			containerID: 'toTop', // fading element id
											containerHoverID: 'toTopHover', // fading element hover id
											scrollSpeed: 1200,
											easingType: 'linear' 
								 		};
										*/
										
										$().UItoTop({ easingType: 'easeOutQuart' });
										
									});
								</script>
		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>


<!--JS-->
<script type="text/javascript" src="/js/bootstrap-3.1.1.min.js"></script>

<!--//JS-->

 </div>

</body>
</html>

app/views/main/contacts.html.erb
<h1>Members of AIR</h1>
<div class="main-content" style="margin-bottom:-50px">
<div class="media response-info" style="margin-top:-50px">
    <div class="response-text-left">
<table>
  <tr>
    <td></td>
    <td>학번</td>
    <td>이름</td> 
    <td>이메일</td>
    <td>현거주도시</td>
    <td>전화#</td>
  </tr>
<% @users.each do |urs| %>
  <tr>
    <% if urs.image.url %>
    <td><img src="<%=urs.image.url%>" width="30px" height="30px"></td>
    <% else %>
    <td><img src="/images/p2.jpg" width="30px" height="30px"></td>
    <% end %>
    <td><%=urs.classid%></td>
    <td><%= link_to profile_path(urs.id) do %><%=urs.username%><% end %></td>    
    <td><%=urs.email%></td>
    <td><%=urs.aloca%></td>
    <td><%=urs.phone%></td>
  </tr>

<% end %>    
    
</table>
		           <div class="clearfix"> </div>
  </div>
</div>
</div>